### PR TITLE
fix: public inputs retrieval

### LINKED ISSUE #128: Fix public inputs retrieval in `aggchain-proof-contracts`

### PR DESCRIPTION
**Pull request by atanmarko**
# Description

Update/cleanup public inputs retrieval

Fixes #128 

## PR Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added or updated tests that comprehensively prove my change is effective or that my feature works

### CODE REVIEW

File: crates/aggchain-proof-contracts/src/config.rs [hunk 1]
```diff
@@ -51,7 +51,7 @@ impl Default for AggchainProofContractsConfig {
 pub(crate) fn default_output_at_block_endpoint() -> String {
     from_env_or_default(
         "L2_OUTPUT_AT_BLOCK_ENDPOINT",
```
Comment (Ekleog-Polygon) [inline crates/aggchain-proof-contracts/src/config.rs:53]: Do we want to also update the env var naming?

**Review by Ekleog-Polygon — APPROVED** [review]
LGTM! I'm just thinking we should also update the env var name 😄

File: crates/aggchain-proof-contracts/src/config.rs (hunk 1 above)
Comment (atanmarko) [reply crates/aggchain-proof-contracts/src/config.rs:53]: I think env naming is appropriate here, deliberately left it like that.

Comment (Ekleog-Polygon) [reply crates/aggchain-proof-contracts/src/config.rs:53]: 👍 you know better than I what's the expected behavior for users of aggkit-prover
